<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="1" failed="0" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-04-19T23:51:42 IST" name="Default suite" finished-at="2022-04-19T23:52:16 IST" duration-ms="34111">
    <groups>
    </groups>
    <test started-at="2022-04-19T23:51:42 IST" name="Default test" finished-at="2022-04-19T23:52:16 IST" duration-ms="34111">
      <class name="com.vva.inetbanking.testcases.AddNewCustomerTC001">
        <test-method is-config="true" signature="init()[pri:0, instance:com.vva.inetbanking.testcases.AddNewCustomerTC001@16d04d3d]" started-at="2022-04-19T23:51:40 IST" name="init" finished-at="2022-04-19T23:51:42 IST" duration-ms="2161" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:com.vva.inetbanking.testcases.AddNewCustomerTC001@16d04d3d]" started-at="2022-04-19T23:51:42 IST" name="setup" finished-at="2022-04-19T23:51:52 IST" duration-ms="10000" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="addNewCustomerTest()[pri:0, instance:com.vva.inetbanking.testcases.AddNewCustomerTC001@16d04d3d]" started-at="2022-04-19T23:51:52 IST" name="addNewCustomerTest" finished-at="2022-04-19T23:52:15 IST" duration-ms="23093" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addNewCustomerTest -->
        <test-method is-config="true" signature="teardown(org.testng.ITestResult)[pri:0, instance:com.vva.inetbanking.testcases.AddNewCustomerTC001@16d04d3d]" started-at="2022-04-19T23:52:15 IST" name="teardown" finished-at="2022-04-19T23:52:15 IST" duration-ms="10" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=addNewCustomerTest status=SUCCESS method=AddNewCustomerTC001.addNewCustomerTest()[pri:0, instance:com.vva.inetbanking.testcases.AddNewCustomerTC001@16d04d3d] output={null}]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "com.aventstack.extentreports.ExtentTest.log(com.aventstack.extentreports.Status, String)" because "this.extentTest" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "com.aventstack.extentreports.ExtentTest.log(com.aventstack.extentreports.Status, String)" because "this.extentTest" is null
at com.vva.inetbanking.testbase.TestBase.teardown(TestBase.java:95)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:700)
at org.testng.internal.TestInvoker.runAfterGroupsConfigurations(TestInvoker.java:676)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:660)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="flushReport()[pri:0, instance:com.vva.inetbanking.testcases.AddNewCustomerTC001@16d04d3d]" started-at="2022-04-19T23:52:15 IST" name="flushReport" finished-at="2022-04-19T23:52:16 IST" duration-ms="875" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- flushReport -->
      </class> <!-- com.vva.inetbanking.testcases.AddNewCustomerTC001 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
